name: Deploy

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'index.html'

jobs:
  update:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Setup git
        run: |
          git config --local user.email "github-actions[bot]@github.com"
          git config --local user.name "github-actions[bot]"
      - name: Build
        run: |
          bun install
          bun build.js
      - name: Commit changes
        run: |
          git add .
          git commit -m "[bot] AUTO UPDATE"
      - name: Push master branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
